---
- name: Install python3 via packagemgr
  block:
    - name: Install system packages
      become: true
      yum:
        name:
          - python-setuptools
          - python3
          - python3-pip
        state: present

    - name: Install utilities
      become: true
      pip:
        name:
          - virtualenv
          - pipenv
        state: present
        executable: pip3

  when: python_version == None

- name: install pyenv build dependencies
  yum:
    name:
      - libffi-devel
      - zlib-devel
      - bzip2-devel
      - readline-devel
      - sqlite-devel
      - wget
      - curl
      - llvm
      - ncurses-devel
      - openssl-devel
      - lzma-sdk-devel
      - libyaml-devel
      - redhat-rpm-config
      - make
    state: present
  when: python_version != None
  become: true
