---
- name: install Python via pyenv
  block:
    - name: create temporary build dir
      tempfile:
        state: directory
        suffix: build
      register: python_build_dir

    - name: install pyenv
      block:
        - name: download installer
          get_url:
            url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
            dest: "{{ python_build_dir.path }}"
          changed_when: false

        - name: run installer
          command: "bash pyenv-installer"
          args:
            chdir: "{{ python_build_dir.path }}"
            creates: "{{ ansible_user_dir }}/.pyenv"

        - name: update rc file
          blockinfile:
            path: "{{ python_rcfile }}"
            create: true
            block: |
              export PATH="{{ ansible_user_dir }}/.pyenv/bin:$PATH"
              eval "$(pyenv init -)"
              eval "$(pyenv virtualenv-init -)"

        - name: update pyenv
          command: pyenv update

    - name: install python
      block:
        - name: install python
          command: "pyenv install {{ python_version }}"
          args:
            creates: "{{ ansible_user_dir }}/.pyenv/versions/{{ python_version }}"

        - name: run pyenv rehash
          command: "pyenv rehash"

        - name: get python<major.minor> executable
          set_fact: python_executable="python{{ python_major }}.{{ python_minor }}"
          vars:
            version_list: "{{ python_version.split('.') }}"
            python_major: "{{ version_list[0] }}"
            python_minor: "{{ version_list[1] }}"

        - name: create symlink to /usr/bin/
          file:
            src: "{{ ansible_user_dir }}/.pyenv/versions/{{ python_version }}/bin/{{ python_executable }}"
            dest: "/usr/bin/{{ python_executable }}"
            state: link
          become: true
