---
- name: install python3 via packagemgr (apt)
  block:
    - name: install system packages
      become: true
      apt:
        name:
          - python-setuptools
          - python3-setuptools
          - python3
          - python3-pip
          - virtualenv
        state: present

    - name: install utilities
      become: true
      pip:
        name:
          - pipenv
        state: present
        executable: pip3

  when: python_version == None

- name: install pyenv build dependencies
  apt:
    name:
      - curl
      - gcc
      - git
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - zlib1g-dev
      - make
    state: present
  when: python_version != None
  become: true
